### ISSUE TITLE
launch checklist

### ISSUE THREAD

**Issue by snd** [snd/rust_solc#1]
- [x] compile with solc
- [x] add ethabi to example
- [x] add .travis.yml
- [x] make public
- [x] make travis build work for solc
- [x] json string in / json string out
- [x] decide whether to drop solcjs support or drop standard json and messily normalize differences
- [x] rename files after solcjs
- [x] rename files containing directory sections correctly
- ~generate json input for common case~
- ~parse json output for common case~
- [x] make travis build work for solcjs
- [x] `compile` with any available version
- [x] pin rust version on travis
- [x] check rustfmt on travis
- [ ] generate documentation on travis
- [ ] add docstrings to every function
- [ ] link documentation in readme
- [ ] link and explain example in readme
- [ ] add `chain_err` to add  context to errors
- [x] add travis badge
- [x] more helpful display for `NoSolidityCompilerFound` (include links to instructions)
- [x] mass compile all contracts in a directory
- [ ] add LICENSE
